### ISSUE TITLE
can we make a decentralised issue tracker from that? 

### ISSUE THREAD

**Issue by pierreozoux** [dominictarr/bittodo#1]

**Comment by dominictarr** [comment]
Yes, they are basically the same but issue tracker is also about discussion.
In a way you could regard each post/comment as a task for some one.
You basically just assigned me the task of answering your question.

Really, at this phase bittodo is intended to be an experiment with the sorts of things we can build on top of [ssb](https://github.com/ssbc). We already have a discussion system implemented (phoenix)

bittodo has editable tasks (need state=>done at a minimum) and tasks can be linked to dependent tasks (not necessarily a "subtask" because a multiple tasks could share a dependent task. Tasks can also be assigned to other people...

Really I'm working on what we need to build bittodo, rather than bittodo, so most of it will be useful for other similar stuff.

**Comment by pierreozoux** [comment]
Great :) I don't yet understand exactly how this works, but looks promising! Thanks for your time!

**Comment by dominictarr** [comment]
@pierreozoux if you want to learn more, look at secure-scuttlebutt and scuttlebot.

**Comment by pierreozoux** [comment]
Yes, I heard those, as some people want me to host it for them. I have to dig on it :)

**Comment by dominictarr** [comment]
oh, cool. you work on indiehosters! if you have questions, come hangout in #scuttlebutt
